### ISSUE TITLE
Support for device userdata?

### ISSUE THREAD

**Issue by benjamink** [ebsarr/packet#10]
Will userdata (cloud-init or scripts) be supported at some point?

**Comment by ebsarr** [comment]
Yes. What command line syntax would be the most suitable for you?

**Comment by benjamink** [comment]
I was thinking passing a file containing the script.  I wonder if being able to submit the script in-line as a string would be helpful too, though? 

```
-u, --userdata <filename>
```

**Comment by ebsarr** [comment]
@benjamink: Submitting the script in-line might require ugly escape sequences. This is the reason why I dropped the support for userdata in the first place. Indeed, passing a file containing the script is a clean way to do it. Thanks for the advice. Will work on it in the following days.

**Comment by ebsarr** [comment]
https://github.com/ebsarr/packet/commit/ff2f8446ce90906cfd40a4332fcff7280599cde4
