### ISSUE TITLE
Add support for spot market

### ISSUE THREAD

**Issue by vielmetti** [ebsarr/packet#14]
Packet now has support for a "spot market" for interruptible, reduced price instances. There's a brief bit of documentation at

https://help.packet.net/technical/deployment-options/spot-market

Two commands to add to support this:

* `packet admin spot-prices` - "will provide the current prices for each Packet facility and plan."
* `packet baremetal create-device` - add optional flag to set spot market price bid (spot_price_max) 

I think the first of these is relatively straightforward; the second one, perhaps will take a little thinking, especially in handling error conditions.

**Comment by ebsarr** [comment]
@vielmetti : I'm starting to catch up with the additions in the packet API. For the spot instance creation, do the flags below make sense?

- `--spot-instance` : set the `spot_instance` parameter in the API call true, 

- `spot-price-max`: set spot market price bid

For the error handling part I'll run some tests and see what happens, as it's not obvious from the docs.

**Comment by vielmetti** [comment]
Thanks @ebsarr . If you run into weird error conditions report them here and I'll make sure they get a review and that the documentation gets updated anywhere it's unclear. Your plan sounds good to me.

**Comment by ebsarr** [comment]
@vielmetti : try v2.1
