### ISSUE TITLE
Failed to build since some packngo structures' fields is updated

### ISSUE THREAD

**Issue by crystaldust** [ebsarr/packet#15]
I tried to build the latest packet project but got the error:
```
cmd/api.go:161: unknown field 'HostName' in struct literal of type packngo.DeviceCreateRequest
cmd/api.go:188: unknown field 'HostName' in struct literal of type packngo.DeviceCreateRequest
```
This is caused by some field names update of the [packngo](https://github.com/packethost/packngo) project, commit [here](https://github.com/packethost/packngo/commit/c955c4d360b92d4aef9ebd4553952a1b07a92c12). Since golang doesn't provide a solid versioning system, I'm not sure if you guys are going to change the reference to fields or make a version constraint?

**Comment by mmcquillan** [comment]
@crystaldust Should be resolved now that this was merged. https://github.com/ebsarr/packet/pull/16
