### ISSUE TITLE
Add doc for spot market

### ISSUE THREAD

**Issue by vielmetti** [ebsarr/packet#18]
v2.1 adds support for spot market in #14 (thanks!) 

The PR to close this updates the supporting documentation. (I'm happy to help once I figure out how  docs are generated).

**Comment by vielmetti** [comment]
"Auto generated by spf13/cobra on 20-Nov-2016" - how does this work?

**Comment by ebsarr** [comment]
Oh sorry I forgot to update the docs. There is a hidden command `packet gendoc` that you can use to do this. It's updated now.

**Comment by ebsarr** [comment]
@vielmetti : Updated the README.md with an overview of available commands, plus your doc for spot market. I think this is better than having to browse in the details.
