### ISSUE TITLE
"updateDeviceCmd" action for baremetal

### ISSUE THREAD

**Issue by sygibson** [ebsarr/packet#23]
Love the tool - simple - fast, easy to use ... thank you ! 

Looking through the baremetal.go code, it appears there's no way to update an existing baremetal machine.   As a user I'd like to be able to modify existing baremetal machines with new values. 

For example:

  packet baremetal update-device --id <UUID> --file userdata.txt
or
  packet baremetal update-device --id <UUID> --hostname fred

**Comment by ebsarr** [comment]
WIP

**Comment by ebsarr** [comment]
@sygibson : I pushed an update to a new branch [v2.2](https://github.com/ebsarr/packet/commit/0e4e854c08d1b9fce7b31f5fc8259a341b22a95b) to address this request as well as #24 and #25 . Could you help by running some tests? Thanks.

**Comment by ebsarr** [comment]
@vielmetti : 

I implemented the `update-device` command, with empty strings or `false` boolean value for the accepted parameters by default .  This allows to do `packet baremetal update-device --hostname my-host-name` without modifying the other parameters. Some test results:

### Device info
`$ packet baremetal list-device --device-id 78e57da0-be43-4ae1-979b-3494acc8c249`

```json
{
    "id": "78e57da0-be43-4ae1-979b-3494acc8c249",
    "href": "/devices/78e57da0-be43-4ae1-979b-3494acc8c249",
    "hostname": "78e57da0.packethost.net",
    "state": "active",
    "created_at": "2018-03-11T04:59:16Z",
    "updated_at": "2018-03-11T05:03:59Z",
    "billing_cycle": "hourly",
    "ip_addresses": []
}
```

### Update hostname
`$ packet baremetal update-device --hostname nrt1-ebsarrtest01 --device-id 78e57da0-be43-4ae1-979b-3494acc8c249`

```json
{
    "id": "78e57da0-be43-4ae1-979b-3494acc8c249",
    "href": "/devices/78e57da0-be43-4ae1-979b-3494acc8c249",
    "hostname": "nrt1-ebsarrtest01",
    "state": "active",
    "created_at": "2018-03-11T04:59:16Z",
    "updated_at": "2018-03-11T05:14:02Z",
    "billing_cycle": "hourly",
    "ip_addresses": []
}
```

### Update description
`$ packet baremetal update-device --description 'Device created to test packet command line v2.2' --device-id 78e57da0-be43-4ae1-979b-3494acc8c249`

```json
{
    "id": "78e57da0-be43-4ae1-979b-3494acc8c249",
    "href": "/devices/78e57da0-be43-4ae1-979b-3494acc8c249",
    "hostname": "78e57da0.packethost.net",
    "state": "active",
    "created_at": "2018-03-11T04:59:16Z",
    "updated_at": "2018-03-11T05:17:46.771Z",
    "billing_cycle": "hourly",
    "ip_addresses": []
}
```

Notice that after the second update, the hostname was reverted back to the one assigned by default   when provisioning the device. Is this the expected result, or did I miss something on how to use this API? 
And by the way, how can I verify the device description? The API does not return any description value, neither could I find it in the portal...

**Comment by vielmetti** [comment]
Thanks @ebsarr - it looks like when our portal changed that some parts of the UI omitted the device description. We have an internal ticket to track this which I'll update here when it's addressed.

**Comment by ebsarr** [comment]
@vielmetti : Thanks. I've posted a question to packet CS to follow up on the other question.

**Comment by ebsarr** [comment]
Issue fixed in latest release.
