### ISSUE TITLE
add always_pxe option to create-device (and future "update-device")

### ISSUE THREAD

**Issue by sygibson** [ebsarr/packet#24]
Packet supports setting "always_pxe" to true - which forces the machine to ALWAYS (ahem...) PXE boot every time, instead of on the first provisioning attempt.   This in conjunction with "userdata" specifying alternate iPXE options enables complete control of a machine with non-Packet provisioning systems. 

I'd like to ask that "baremetal create-device" command include an "--always_pxe=true" option. 

Subsequently, when/if "baremetal update-device" is added, that this feature be added to support setting "always_pxe" to "true" or "false".   see #23

**Comment by ebsarr** [comment]
WIP

**Comment by ebsarr** [comment]
Feature added in latest update.

**Comment by sygibson** [comment]
Bassirou - v2.2 has a bunch of great additions and cleanups.  Thanks !!!

**Comment by ebsarr** [comment]
@sygibson : I'm not confident about my test coverage. Let me know if you face any bug. Thank you for your feedbacks.
