### ISSUE TITLE
allow "userdata" to be passed via command line string, not just file

### ISSUE THREAD

**Issue by sygibson** [ebsarr/packet#25]
We use "userdata" fairly heavily to change provisioning endpoints regularly.  As an operator, would like to request that a new flag "--userdata" be added to input userdata via string.  Might also suggest moving "--file" to be "--userfile" to pass a file as an alternate option for obtaining userdata.

**Comment by ebsarr** [comment]
WIP

**Comment by ebsarr** [comment]
Feature added in latest release.
