### ISSUE TITLE
Unable to install with go get

### ISSUE THREAD

**Issue by vinitkhandagle** [ebsarr/packet#28]
I am trying to install the tool but getting the below error

```
% go get -u github.com/ebsarr/packet                                                                                                                     
# github.com/ebsarr/packet/cmd
goapps/src/github.com/ebsarr/packet/cmd/api.go:74:16: unknown field 'PaymentMethod' in struct literal of type packngo.ProjectCreateRequest
```

**Comment by vielmetti** [comment]
I was able to confirm the error, which shows up at

https://github.com/ebsarr/packet/blob/master/cmd/api.go#L74

**Comment by ebsarr** [comment]
Thanks for the report. Issue fixed in latest release: v2.1.2. Please confirm @vielmetti @vinitkhandagle .

**Comment by vielmetti** [comment]
Test machine is a Mac running Go 1.9.3 installed from homebrew; I was able to do `go get -u github.com/ebsarr/packet` and compile without any problems.

Also test on Ubuntu 16.04 on a Packet "Type 0" server, compiles and runs without any evident issues.

Looks good to me!

**Comment by vinitkhandagle** [comment]
Issue is fixed thanks
