### ISSUE TITLE
[v2.2.1] Updating user-data blows away all tags

### ISSUE THREAD

**Issue by pgporada** [ebsarr/packet#34]
Hi,

I ran the following command to update the user-data on my servers and was surprised when all the server tags were removed according to the Packet web UI. I don't happen to use the server tags for any reason other than testing, but if someone relies upon them it could cause issues.

```
$ packet --version
2.2.1
```

```
for i in $(packet baremetal list-devices | jq -r '.[].id'); do 
    packet baremetal update-device --device-id ${i} --userfile user-data.txt
done
```

**Comment by ebsarr** [comment]
@pgporada : Found the bug. Sorry this happened to you. I will fix ASAP, stay tuned.

**Comment by ebsarr** [comment]
@pgporada : Issue fixed. Please upgrade to `v2.2.2` and verify :

```sh
$ packet baremetal update-device --device-id aaaa --userdata ""
{
    "id": "aaaa",
    "href": "/devices/aaaa",
    "hostname": "pkt-nrt1-ebsarrtest02",
    "state": "active",
    "created_at": "2018-03-11T04:59:16Z",
    "updated_at": "2018-06-02T15:55:56Z",
    "billing_cycle": "hourly",
    "tags": [
        "test",
        "cli",
        "api"
    ],
...
```
Tags are intact after device update.
Also, Setting tags with `create-device` and modifying tags with `update-device` are now available with the newly added `--tags` flag:
Create device with tags
```sh
$ packet baremetal create-device --facility nrt1 --hostname testing-tags --tags "test,cli,api"
```
Modify tags
```sh
packet baremetal update-device --device-id bbb --tags "test,cli,api"
```
