### ISSUE TITLE
'packet storage create-volume --count 0'

### ISSUE THREAD

**Issue by ghost** [ebsarr/packet#36]
Hello! 
Could you please allow creation of volumes without snapshot usage at all?

**Comment by ebsarr** [comment]
I am afraid the API does not allow to create a snapshot policy with 0 count. And at least one snapshot policy is a mandatory parameter when creating a volume. See https://www.packet.net/developers/api/volumes/

@vielmetti : Do you have any advise on this ?

**Comment by ghost** [comment]
Thanks for reply! 
Well, via Web console it's possible to create Volume without Snapshot Policy. 
I also tried to remove the Snapshot Policy after creation via 'packet storage delete-snapshot-policy', but don't able to find ID string for '--policy-id'. Where is it?

**Comment by vielmetti** [comment]
Thanks @ebsarr @inemylostyvyi - I've pinged @mmlb to see what he thinks.

**Comment by mmlb** [comment]
@ebsarr thankfully the new portal goes straight to api so if in doubt fireup browser console :raised_hands:!! So api will be just fine if you send an empty array for `snapshot_policies`, it may even be fine if you omit it too.

**Comment by ebsarr** [comment]
@mmlb thanks. I’ll modify the code to pass an empty slice of `snapshot_policies` and see how it behaves .

**Comment by ebsarr** [comment]
@inemylostyvyi : I have addressed the issue in `v2.3.1`.

**Comment by ghost** [comment]
@ebsarr Thanks!
